name: rocm-football

services:
  football:
    image: rocm-football
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    security_opt:
      - seccomp:unconfined
    group_add:
      - video
      - render

    container_name: rocm-football-container
    hostname: rocm-football

    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    # volumes:
      # - ${VIDEOS_PATH}:/videos

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

    # environment:
    #   - NVIDIA_DRIVER_CAPABILITIES=all

    # shm_size: '64gb'
